const halls = [
  {
    name: 'INOX DIGITAL',
    id: '1',
    address: 'Mall Road',
    state: 'Gangtok',
    imageUrl:
      'https://images.pexels.com/photos/53464/sheraton-palace-hotel-lobby-architecture-san-francisco-53464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    movies: [
      {
        id: '101',
        name: 'The Kashmir Files',
        description: 'truth',
        type: 'history',
        duration: '2.34',
        rating: '10',
        movieImage:
          ' https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQmKgP4vLRXSTqSH267sCvY3l9u5Sqr6FgdGtnFU82-66QAJNL2',
        releaseDate: '',
        releaseYear: '',
        shows: [
          {
            id: 201,
            date: '27/03/22',
            language: 'Hindi',
            availableSeatsRow: '2',
            availableSeatsCol: '10',
            seats: [
              { id: 301, row: '1', col: '1', isSelected: false },
              { id: 302, row: '1', col: '2', isSelected: false },
              { id: 303, row: '1', col: '3', isSelected: false },
              { id: 304, row: '1', col: '4', isSelected: false },
              { id: 305, row: '1', col: '5', isSelected: false },
              { id: 306, row: '1', col: '6', isSelected: false },
              { id: 307, row: '1', col: '7', isSelected: false },
              { id: 308, row: '1', col: '8', isSelected: false },
              { id: 309, row: '1', col: '9', isSelected: false },
              { id: 310, row: '1', col: '10', isSelected: false },
              { id: 311, row: '2', col: '1', isSelected: false },
              { id: 312, row: '2', col: '2', isSelected: false },
              { id: 313, row: '2', col: '3', isSelected: false },
              { id: 314, row: '2', col: '4', isSelected: false },
              { id: 315, row: '2', col: '5', isSelected: false },
              { id: 316, row: '2', col: '6', isSelected: false },
              { id: 317, row: '2', col: '7', isSelected: false },
              { id: 318, row: '2', col: '8', isSelected: false },
              { id: 319, row: '2', col: '9', isSelected: false },
              { id: 320, row: '2', col: '10', isSelected: false },
            ],
          },
        ],
      },
      {
        id: '101',
        name: 'Harry Potter',
        description: 'magic',
        type: 'magic',
        duration: '2.16',
        rating: '7',
        movieImage:
          'https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg',
        releaseDate: '',
        releaseYear: '',
        shows: [
          {
            id: 801,
            date: '27/03/22',
            language: 'Hindi',
            availableSeatsRow: '2',
            availableSeatsCol: '10',
            seats: [
              { id: 901, row: '1', col: '1', isSelected: false },
              { id: 902, row: '1', col: '2', isSelected: false },
              { id: 903, row: '1', col: '3', isSelected: false },
              { id: 904, row: '1', col: '4', isSelected: false },
              { id: 905, row: '1', col: '5', isSelected: false },
              { id: 906, row: '1', col: '6', isSelected: false },
              { id: 907, row: '1', col: '7', isSelected: false },
              { id: 908, row: '1', col: '8', isSelected: false },
              { id: 909, row: '1', col: '9', isSelected: false },
              { id: 910, row: '1', col: '10', isSelected: false },
              { id: 911, row: '2', col: '1', isSelected: false },
              { id: 912, row: '2', col: '2', isSelected: false },
              { id: 913, row: '2', col: '3', isSelected: false },
              { id: 914, row: '2', col: '4', isSelected: false },
              { id: 915, row: '2', col: '5', isSelected: false },
              { id: 916, row: '2', col: '6', isSelected: false },
              { id: 917, row: '2', col: '7', isSelected: false },
              { id: 918, row: '2', col: '8', isSelected: false },
              { id: 919, row: '2', col: '9', isSelected: false },
              { id: 920, row: '2', col: '10', isSelected: false },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'City Mall',
    id: '2',
    address: 'Mall Road',
    state: 'Gangtok',
    imageUrl:
      'https://images.pexels.com/photos/382297/pexels-photo-382297.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    movies: [
      {
        id: '401',
        name: 'RRR',
        description: 'Action',
        type: 'Action',
        duration: '2.14',
        rating: '8',
        movieImage:
          'https://upload.wikimedia.org/wikipedia/en/d/d7/RRR_Poster.jpg',
        releaseDate: '',
        releaseYear: '',
        shows: [
          {
            date: '27/03/22',
            language: 'Hindi',
            availableSeatsRow: '2',
            availableSeatsCol: '10',
            seats: [
              { id: 501, row: '1', col: '1', isSelected: false },
              { id: 501, row: '1', col: '2', isSelected: false },
              { id: 501, row: '1', col: '3', isSelected: false },
              { id: 501, row: '1', col: '4', isSelected: false },
              { id: 501, row: '1', col: '5', isSelected: false },
              { id: 501, row: '1', col: '6', isSelected: false },
              { id: 501, row: '1', col: '7', isSelected: false },
              { id: 501, row: '1', col: '8', isSelected: false },
              { id: 501, row: '1', col: '9', isSelected: false },
              { id: 501, row: '1', col: '10', isSelected: false },
              { id: 501, row: '2', col: '1', isSelected: false },
              { id: 501, row: '2', col: '2', isSelected: false },
              { id: 501, row: '2', col: '3', isSelected: false },
              { id: 501, row: '2', col: '4', isSelected: false },
              { id: 501, row: '2', col: '5', isSelected: false },
              { id: 501, row: '2', col: '6', isSelected: false },
              { id: 501, row: '2', col: '7', isSelected: false },
              { id: 501, row: '2', col: '8', isSelected: false },
              { id: 501, row: '2', col: '9', isSelected: false },
              { id: 501, row: '2', col: '10', isSelected: false },
            ],
          },
        ],
      },
    ],
  },
]

export default halls
